[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
optivault = "GAKRYNWn7YjHQB8ihiBYYn1QVp2g4vVt8wtTyEK65syZ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
